[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "GridSolverPlus"
description = "Automatically place selected upgrades on the hex grid. Hover and press N to select, then Solve."
websiteUrl = "https://github.com/Little-Sparroh/GridSolverPlus"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"
Sparroh-SparrohUILib = "1.1.1"


[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/GridSolverPlus.dll"
target = "BepInEx/plugins/GridSolverPlus.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
